catcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('cats/', views.cats_index, name='cats_index'),
    path('cats/<int:cat_id>/', views.cats_show, name='cats_show'),
    path('cats/create/', views.CatCreate.as_view(), name='cats_create'),
    path('cats/<int:pk>/update/', views.CatUpdate.as_view(), name='cats_update'),
    path('cats/<int:pk>/delete/', views.CatDelete.as_view(), name='cats_delete'),
    path('user/<username>/', views.profile, name='profile'),
    path('cattoys/', views.cattoys_index, name='cattoys_index'),
    path('cattoys/<int:cattoy_id>', views.cattoys_show, name='cattoys_show'),
    path('cattoys/create/', views.CatToyCreate.as_view(), name='cattoys_create'),
    path('cattoys/<int:pk>/update/', views.CatToyUpdate.as_view(), name='cattoys_update'),
    path('cattoys/<int:pk>/delete/', views.CatToyDelete.as_view(), name='cattoys_delete'),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('signup/', views.signup, name='signup'),
    path('user/<username>/', views.profile, name='profile'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class CatToy(models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=50)

    def __str__(self):
        return self.name
        
class Cat(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    age = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cattoys = models.ManyToManyField(CatToy)

    def __str__(self):
        return self.name

main_app/views.py
from django.shortcuts import render, redirect
from .models import Cat, CatToy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# Create your views here.
@login_required
def profile(request, username):
    user = User.objects.get(username=username)
    cats = Cat.objects.filter(user=user)
    return render(request, 'profile.html', {'username': username, 'cats': cats})
    
def about(request):
    return render(request, 'about.html')

def index(request):
    return render(request, 'index.html')

def login_view(request):
# if post, then authenticate (user submitted username and password)
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            u = form.cleaned_data['username']
            p = form.cleaned_data['password']
            user = authenticate(username = u, password = p)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/user/'+u)
                else:
                    print('The account has been disabled.')
                    return HttpResponseRedirect('/')
        else:
            print('The username and/or password is incorrect.')
            return HttpResponseRedirect('/login')
    else: # it was a get request so send the emtpy login form
        form = AuthenticationForm()
        return render(request, 'login.html', {'form': form})

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/cats')

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
        return render(request, 'signup.html', {'form': form})

# CRUD FOR CAT MODEL

def cats_index(request):
    cats = Cat.objects.all()
    data = { 'cats': cats }
    return render(request, 'cats/index.html', data)

def cats_show(request, cat_id):
    cat = Cat.objects.get(id=cat_id)
    data = { 'cat': cat }
    return render(request, 'cats/show.html', data)

# forms - generic from django
class CatCreate(CreateView):
    model = Cat
    fields = ['name', 'breed', 'description', 'age']

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect('/cats/' + str(self.object.pk))

class CatUpdate(UpdateView):
    model = Cat
    fields = ['name', 'breed', 'description', 'age', 'cattoys']

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        return HttpResponseRedirect('/cats/' + str(self.object.pk))

@method_decorator(login_required, name='dispatch')
class CatDelete(DeleteView):
    model = Cat
    success_url = '/cats'

# CRUD FOR CATTOY MODEL
def cattoys_index(request):
    cattoys = CatToy.objects.all()
    return render(request, 'cattoys/index.html', {'cattoys': cattoys})

def cattoys_show(request, cattoy_id):
    cattoy = CatToy.objects.get(id=cattoy_id)
    return render(request, 'cattoys/show.html', {'cattoy': cattoy})

class CatToyCreate(CreateView):
    model = CatToy
    fields = '__all__'
    success_url = '/cattoys'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect('/cattoys')


class CatToyUpdate(UpdateView):
    model = CatToy
    fields = ['name', 'color']
    success_url = '/cattoys'

class CatToyDelete(DeleteView):
    model = CatToy
    success_url = '/cattoys'

main_app/templates/about.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>About the catcollector...</title>
	</head>
	<body>
		<h1>About the catcollector...</h1>
		<hr />
		<p>Hire the catcollector!</p>
		<footer>
			All Rights Reserved, CatCollector 2021
		</footer>
	</body>
</html>

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
    <title>CatCollector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.css">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>
    <body>
        <nav>
            <div class="nav-wrapper">
            <a href="/cats" class="brand-logo">CatCollector</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                {% if user.is_authenticated %}
                <li><a href="{% url 'profile' user.username %}">Hello, {{ user.username }}!</a></li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'login' %}">Login</a></li>
                <li><a href="{% url 'signup' %}">SignUp</a></li>
                {% endif %}
            </ul>
            </div>
        </nav>

        {% block content %}
        {% endblock %}

        <hr />
        <footer class="footerWrapper">
            <div class="container">
                <div>All Rights Reserved, catcollector 2021</div>
            </div>
    </footer>
    </body>
</html>

main_app/templates/cats/index.html
<!-- templates/cats/index.html -->


<!-- main_app/templates/index.html -->
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="heading">
    <h1>Gallery</h1>
</div>
<hr />
<div class="btn_container">
    <a href="/cats/create" class="waves-effect waves-light btn">Add a New Cat!</a>
</div>

<section class="gallery">

<div class="row">
    {% for cat in cats %}

    <div class="col s12 m10 l3 xl2 gallery__item">
        <p>Name: {{ cat.name }}</p>
    
    <p>Adopted By: <a href='/user/{{cat.user.username}}'>{{cat.user.username}}</a></p>
    {% if cat.age > 0 %}
        <p>Age: {{ cat.age }}</p>
    {% else %}
        <p>Age: Kitten</p>
    {% endif %}
    <a href="{% url 'cats_show' cat.id %}">See Details</a> 

    </div>
    {% endfor %}
</div>
</section>
    
{% endblock %}

main_app/templates/cats/show.html
{% extends 'base.html' %}
{% block content %}
    <!-- templates/cats/detail.html -->
<div class="card-content">
    <span class="card-title">{{ cat.name }}</span>
    <p>Breed: {{ cat.breed }}</p>
    <p>Description: {{ cat.description }}</p>
    <p>Owner: {{ cat.user }}</p>
    {% if cat.age > 0 %}
        <p>Age: {{ cat.age }}</p>
    {% else %}
        <p>Age: Kitten</p>
    {% endif %}
    {% for cattoy in cat.cattoys.all %}
    <div>{{cattoy.name}}</div>
{% empty %}
    <div>Cat Has No Toys :(</div>
{% endfor %}
    <!-- Add links for update and delete here... -->
    <a href="{% url 'cats_update' cat.id %}" class="waves-effect waves-light btn">Update Details</a>
    <a href="{% url 'cats_delete' cat.id %}" class="waves-effect waves-light btn">DELETE This Cat</a>
</div>
{% endblock %}

main_app/templates/cattoys/index.html
<!-- templates/cattoys/index.html -->
{% extends 'base.html' %}
{% block content %}

<h1>Cat Toy List</h1>

{% for cattoy in cattoys %}
    <div>
        <a href="{% url 'cattoys_show' cattoy.id %}">
            <div class="card-content">
                <span>{{ cattoy.name }}</span>
                <p>Color: {{ cattoy.color }}</p>
            </div>
        </a>
    </div>
{% endfor %}

{% endblock %}

main_app/templates/cattoys/show.html
<!-- templates/cattoys/show.html -->
{% extends 'base.html' %}
{% block content %}

<h1>Cat Toy Details</h1>

<div>
    <div>
        <span>{{ cattoy.name }}</span>
        <p>Color: {{ cattoy.color }}</p>
        <p>Owned by:</p>
        {% for cat in cattoy.cat_set.all %}
            <p>{{cat.name}}</p>
        {% empty %}
            <p>Nobody Has This Toy</p>
        {% endfor %}
    </div>
    <div>
        <a href="{% url 'cattoys_update' cattoy.id %}">Edit</a>
        <a href="{% url 'cattoys_delete' cattoy.id %}">Delete</a>
    </div>
</div>
{% endblock %}

main_app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>catcollector</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.css">
        <link rel="stylesheet" type="text/css" href="{% static 'home.css' %}">
	</head>
	<body>
        <div class="indexWrapper">
            <div class="row">
                <div class="col s6">
                    <h1>Welcome to Catcollector</h1>
                    <p>A den to collect cats to your hearts desire</p>
                    <div class="btn_container">
                        <a href="/cats" class="waves-effect waves-light btn">Enter site</a>
                    </div>
                </div>
            </div>
        </div>
		<footer class="footerWrapper">
                <div class="container">
                    <div>All Rights Reserved, catcollector 2021</div>
                </div>
		</footer>
	</body>
</html>

main_app/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Login</h1>
<form method="POST" action=".">
{% csrf_token %}
{{ form.as_p}}
<input type="submit" value="Submit" />
</form>

{% endblock %}

main_app/templates/main_app/cat_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Cat</h1>

<p>Are you sure you want to delete this cat: {{ cat }}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

main_app/templates/main_app/cat_form.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!">
</form>
{% endblock %}

main_app/templates/main_app/cattoy_confirm_delete.html
<!-- main_app/templates/main_app/cattoy_confirm_delete.html -->
{% extends 'base.html' %}

{% block content %}
    <h1>Delete Cat Toy</h1>

    <h4>Are you sure you want to delete <strong>{{ cattoy }}</strong>?</h4>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes - Delete!">
        <a href="{% url 'cattoys_show' cattoy.id %}">Cancel</a>
    </form>
{% endblock %}

main_app/templates/main_app/cattoy_form.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit!">
    </form>
{% endblock %}

main_app/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>{{ username }}'s collection:</h1>

<table>
<thead>
    <tr>
        <th>Name</th>
        <th>Age</th>
        <th>Description</th>
    </tr>
</thead>

{% for cat in cats %}

<tbody>
    <tr>
    <td>{{ cat.name }}</td>
    <td>{{ cat.age }}</td>
    <td><a href="/cats/{{ cat.id }}">See cat profile</a></td>
    </tr>
</tbody>
{% endfor %}
</table>



{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h2>Sign up</h2>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
    </form>
{% endblock %}